---
dist: xenial
install:
  - wget https://github.com/wata727/tflint/releases/download/v0.8.3/tflint_linux_amd64.zip -O /tmp/tflint.zip
  - sudo unzip -d /usr/local/bin/ /tmp/tflint.zip
  - rm /tmp/tflint.zip
script:
  - tflint ./
notifications:
  email: false
  slack:
    secure: s+DFOUtp44kV7wjGu9j6ztR+qKO4KP+uP14RWKrcGPYK/kHWyHek50qA1fS0Pwyr89u0TGdTSF8RhPHwlJ1p992da8/KvE779oKrNKVSVLcCP8bEdAiT7ijsUPY/Hxorp2vqFluTjdNhPIvOTfBOuNIjit50RmDiTTqTO+kK3eox4xM7ewiJyieiQBzVFCT+hU2/Zlauv7NXWwsz5MKKjb4WLbhCjVtIlb3nmSfK9j1t5iO6TYI1H32ABfw2w0FahN5HxUQizPtU7b/GG2Dx4sqoo02deaSqpzLN9Sw5aC49//0APgsWpcus+OfzKRawrs1UQn6o2ldTECzwcNsfsLOZZqqsfCQHmRfucMiEreDcCFkE27OlVc864jE6N/lMEXQjHJ9TCwj79x72Hb3Wk0Yk4j9H4UcswpmfH/rxB9T/jDxK0wDnfMLBO16qgTSWMB0ylg+zidRvbwd+QwANNRuv9fNha99k1SE1ruGBy7OgigMPRKjuDesJflJcqNU60+y7ZwM9SPEsecNGuUG25w2wMylHqs2MJlI64BuarkomrAgK+7hZpkUHOfcK29w9aNoje1ZN6+jr6jeHJm8uG8gyo1AUElWh1fHidKxCM6cSxtby+qReiIXMF08rdJ1A//t3afR7BwYyxBN6JpSplcuQGLjjNQuM+8Hndfj7qe0=
