name: fmt

on: [push]

env:
  TF_VERSION: 1.0.9

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TF_VERSION }}

      - name: terraform format
        run: terraform fmt -no-color -check -recursive -diff
