name: tfsec

on: [push]

env:
  TFSEC_VERSION: 0.39.26

jobs:
  tfsec:
    name: tfsec

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install tfsec
        run: |
          curl -L https://github.com/tfsec/tfsec/releases/download/v${TFSEC_VERSION}/tfsec-linux-amd64 > /tmp/tfsec
          chmod +x /tmp/tfsec
          sudo mv /tmp/tfsec /usr/local/bin

      - name: Terraform security scan
        run: tfsec
