name: tfsec

on: [push]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # NOTE: ignore setting
      #       AWS002: s3 logging
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
        with:
          tfsec_exclude: AWS002
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
